FROM python:3.8.1
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt
COPY . /app

EXPOSE 8000

ENTRYPOINT [ "python" ]

CMD [ "post_request.py"]